sudo: required

env:
    - DEP_VERSION="0.4.1"

services:
    - docker

branches:
    only:
    - master

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - env
    - docker exec build rpm -q golang
    - docker exec build go version
    - docker exec build git clone https://github.com/Comcast/tr1d1um.git
    - docker exec build git clone https://github.com/Comcast/tr1d1um.git codecovio_build

    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_7bc153b31fc8_key -iv $encrypted_7bc153b31fc8_iv -in keys/RPM-GPG-KEY-comcast-webpa.private.enc -out keys/RPM-GPG-KEY-comcast-webpa.private -d; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker cp keys/RPM-GPG-KEY-comcast-webpa.private build:/RPM-GPG-KEY-comcast-webpa.private; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "gpg --allow-secret-key-import --import /RPM-GPG-KEY-comcast-webpa.private"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker exec build bash -c "pushd tr1d1um; git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge && git checkout -qf FETCH_HEAD; popd"; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker exec build bash -c "pushd codecovio_build; git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge && git checkout -qf FETCH_HEAD; popd"; fi'

    # Download the binary to bin folder in $GOPATH
    - docker exec curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep

    # Make the binary executable
    - docker exec chmod +x $GOPATH/bin/dep


install:
    - docker exec build bash -c "export GOPATH=/codecovio_build && pushd codecovio_build/src && dep ensure && cd tr1d1um && go build tr1d1um && go test -race -coverprofile=coverage.txt && popd"
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "pushd tr1d1um; ./build_rpm.sh; popd"; fi'

after_success:
    - docker exec build bash -c "pushd codecovio_build ; bash <(curl -s https://codecov.io/bash) -t 2781430c-d1d8-4abd-9b17-f329b8fd97ac; popd"
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - docker cp build:/versionno.txt .
    - BINARY_NAME=`ls x86_64/`
    - TRAVIS_TAG=`cat versionno.txt`

deploy:
  provider: releases
  prerelease: true
  api_key: "$AUTH_TOKEN_BUILD"
  file:
    - x86_64/$BINARY_NAME
    - keys/RPM-GPG-KEY-comcast-webpa
  skip_cleanup: true
  on:
    condition: "$TRAVIS_PULL_REQUEST = false"

